package domain

import "time"

// Trade represents a completed or active trade.
type Trade struct {
	ID         string    `json:"id"`
	Symbol     string    `json:"symbol"`
	Strategy   string    `json:"strategy"`
	Side       string    `json:"side"` // BUY or SELL
	EntryPrice float64   `json:"entry_price"`
	EntryTime  int64     `json:"entry_time"` // Unix timestamp
	ExitPrice  float64   `json:"exit_price,omitempty"`
	ExitTime   int64     `json:"exit_time,omitempty"`
	PnL        float64   `json:"pnl,omitempty"`
	Status     string    `json:"status"` // OPEN, CLOSED, REJECTED
}

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	ID          int64   `json:"id"`
	Timestamp   int64   `json:"timestamp"`
	Symbol      string  `json:"symbol"`
	SignalType  string  `json:"signal_type"` // BUY or SELL
	Indicators  string  `json:"indicators"`  // JSON string of indicators
	ActionTaken string  `json:"action_taken"` // EXECUTED / VETOED_BY_RISK
}

// Tick represents a single price update.
type Tick struct {
	Symbol    string    `json:"symbol"`
	Price     float64   `json:"price"`
	Timestamp time.Time `json:"timestamp"`
	Volume    uint64    `json:"volume"`
}
