// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountBalance() {
  return window['go']['main']['App']['GetAccountBalance']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartMarketStream(arg1) {
  return window['go']['main']['App']['StartMarketStream'](arg1);
}
