// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Greet(arg1:string):Promise<string>;

export function GetAccountBalance():Promise<number>;

export function StartMarketStream(arg1:string):Promise<string>;

export function Login(arg1:string, arg2:string):Promise<any>;

export function Register(arg1:string, arg2:string):Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;

export function GetSettings(arg1:number):Promise<any>;

export function SearchStocks(arg1:string):Promise<Array<string>>;

export function PlaceOrder(arg1:string, arg2:number, arg3:string):Promise<void>;

export function GetPortfolio():Promise<Array<any>>;

export function GetRecentTrades():Promise<Array<any>>;
