// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountBalance():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function StartMarketStream(arg1:string):Promise<string>;
