// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GetAccountBalance() {
  return window['go']['main']['App']['GetAccountBalance']();
}

export function StartMarketStream(arg1) {
  return window['go']['main']['App']['StartMarketStream'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function SearchStocks(arg1) {
  return window['go']['main']['App']['SearchStocks'](arg1);
}

export function PlaceOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlaceOrder'](arg1, arg2, arg3);
}

export function GetPortfolio() {
  return window['go']['main']['App']['GetPortfolio']();
}

export function GetRecentTrades() {
  return window['go']['main']['App']['GetRecentTrades']();
}
